[workspace]
resolver = "2"
members = ["assignment2-tester", "tests_lib"]

[workspace.dependencies]
openssl = { version = "0.10", features = ["vendored"] }

[workspace.metadata]
backtrace = "full"

[profile.dev]
debug = true

[profile.release]
debug = true
