[executable]
name = "client"

[test-dir]
name = "testee"

[[tests]]
name = "Usage1"
input = "http://httpbin.org -r 10 pr1=1 pr2=2 pr3=3 pr4=4 pr5=5 pr6=6 pr7=7 pr8=8 pr9=9"

[[tests]]
name = "Usage2"
input = "-r 10 pr1=1 pr2=2 pr3=3 pr4=4 5 pr6=6 pr7=7 pr8=8 pr9=9 pr10=10 http://httpbin.org"

[[tests]]
name = "Validate Request Structure"
input = "http://httpbin.org"

[[tests]]
name = "Validate Request Structure With Params"
input = "-r 1 country=israel http://universities.hipolabs.com"